# Generated by Django 4.1.1 on 2022-09-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_anime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="anime"),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("role", models.CharField(blank=True, max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Anime",
                "verbose_name_plural": "Animes",
                "ordering": ["name"],
            },
        ),
    ]
